version: "3"
services:
  webapp:
    build: ./flask
    env_file:
      - web-variables.env
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    build: ./db
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - /var/lib/mysql